legend:
  fontsize: 12
  loc: "best"
font:
  size: 11
figure:
  figsize: [ 8.0, 6.0 ]
image:
  interpolation: "nearest"
  cmap: "gray"
savefig:
  bbox: "tight"
  format: "svg"
  transparent: True
lines:
  linewidth: 3
  markersize: 6

